import type { LiveArenaDataset, SeasonSummary } from "../lib/types.ts";

interface LiveArenaPanelProps {
  dataset: LiveArenaDataset;
  summary: SeasonSummary;
}

export function LiveArenaPanel({ dataset, summary }: LiveArenaPanelProps) {
  const generatedAt = new Intl.DateTimeFormat("en", {
    dateStyle: "medium",
    timeStyle: "short"
  }).format(new Date(dataset.generatedAt));

  return (
    <section className="panel live-arena">
      <div className="panel__header">
        <div>
          <p className="eyebrow">Live Arena</p>
          <h2>Executed fights from real fixture workspaces</h2>
        </div>
        <p className="panel__copy">
          This card is generated by the live arena runner, not authored by hand. Each corner gets a
          fresh temp workspace, patches actual files, and gets scored from the resulting code.
        </p>
      </div>

      <div className="live-arena__meta">
        <span>{dataset.source}</span>
        <span>{generatedAt}</span>
        <span>{dataset.fights.length} executed fights</span>
        <span>{dataset.tasks.length} fixture tasks</span>
      </div>

      <div className="live-arena__grid">
        <article className="live-arena-card live-arena-card--champion">
          <p className="eyebrow">Live Champion</p>
          <strong>{summary.champion.agent.name}</strong>
          <p>{summary.champion.agent.tagline}</p>
          <div className="live-arena-card__stats">
            <span>{summary.champion.elo} Elo</span>
            <span>
              {summary.champion.wins}-{summary.champion.losses}
            </span>
            <span>{summary.champion.finishes} finishes</span>
          </div>
        </article>

        <article className="live-arena-card">
          <p className="eyebrow">How It Runs</p>
          <ul className="live-note-list">
            {dataset.notes.map((note) => (
              <li key={note}>{note}</li>
            ))}
          </ul>
        </article>
      </div>

      <div className="live-arena__columns">
        <div className="panel panel--inner">
          <p className="eyebrow">Live Ladder</p>
          <h3>Top operators in the current fixture season</h3>
          <div className="live-rankings">
            {summary.rankings.map((row, index) => (
              <article className="live-ranking-row" key={row.agent.id}>
                <span>{String(index + 1).padStart(2, "0")}</span>
                <strong>{row.agent.name}</strong>
                <span>
                  {row.wins}-{row.losses}
                </span>
                <span>{row.elo} Elo</span>
              </article>
            ))}
          </div>
        </div>

        <div className="panel panel--inner">
          <p className="eyebrow">Executed Card</p>
          <h3>Latest generated bouts</h3>
          <div className="live-fight-list">
            {summary.fights.slice(0, 4).map((fight) => {
              const task = summary.taskMap.get(fight.taskId);
              return (
                <article className="live-fight-row" key={fight.id}>
                  <div>
                    <strong>{fight.headline}</strong>
                    <p>{task?.name}</p>
                  </div>
                  <div className="live-fight-row__meta">
                    <span>{fight.finish}</span>
                    <span>{fight.venue}</span>
                  </div>
                </article>
              );
            })}
          </div>
        </div>
      </div>
    </section>
  );
}
