import { useState } from "react";
import type {
  FightCorner,
  FightTranscriptEntry,
  LiveArenaDataset,
  SeasonSummary
} from "../lib/types.ts";

type CornerSide = "blue" | "red";

function formatDuration(durationMs: number | undefined): string | null {
  if (durationMs === undefined) {
    return null;
  }

  return durationMs >= 10_000
    ? `${Math.round(durationMs / 1000)}s runtime`
    : `${(durationMs / 1000).toFixed(1)}s runtime`;
}

function getTranscriptLabel(entry: FightTranscriptEntry): string {
  if (entry.title) {
    return entry.title;
  }

  switch (entry.channel) {
    case "assistant":
      return "Assistant";
    case "stderr":
      return "stderr";
    case "stdout":
      return "stdout";
    case "system":
      return "System";
    case "tool":
      return "Tool";
    case "user":
      return "Task brief";
  }
}

function hasReplayCapture(corner: FightCorner): boolean {
  return Boolean(
    corner.capture?.transcript?.length || corner.capture?.stdoutTail || corner.capture?.stderrTail
  );
}

interface LiveArenaPanelProps {
  dataset: LiveArenaDataset;
  summary: SeasonSummary;
}

export function LiveArenaPanel({ dataset, summary }: LiveArenaPanelProps) {
  const generatedAt = new Intl.DateTimeFormat("en", {
    dateStyle: "medium",
    timeStyle: "short"
  }).format(new Date(dataset.generatedAt));
  const [selectedFightId, setSelectedFightId] = useState(summary.fights[0]?.id ?? "");
  const [selectedCorner, setSelectedCorner] = useState<CornerSide>("blue");

  const selectedFight = summary.fights.find((fight) => fight.id === selectedFightId) ?? summary.fights[0];

  if (!selectedFight) {
    return null;
  }

  const activeCorner = selectedCorner === "blue" ? selectedFight.blue : selectedFight.red;
  const inactiveCorner = selectedCorner === "blue" ? selectedFight.red : selectedFight.blue;
  const activeAgent = summary.agentMap.get(activeCorner.agentId);
  const inactiveAgent = summary.agentMap.get(inactiveCorner.agentId);
  const task = summary.taskMap.get(selectedFight.taskId);
  const transcript = activeCorner.capture?.transcript ?? [];
  const providerSummary = dataset.runMeta?.providers?.join(" / ") ?? "scripted";
  const activeDuration = formatDuration(activeCorner.capture?.durationMs);
  const replayAvailable = hasReplayCapture(selectedFight.blue) || hasReplayCapture(selectedFight.red);

  return (
    <section className="panel live-arena">
      <div className="panel__header">
        <div>
          <p className="eyebrow">Live Arena</p>
          <h2>Executed fights from real fixture workspaces</h2>
        </div>
        <p className="panel__copy">
          This card is generated by the live arena runner, not authored by hand. Each corner gets a
          fresh temp workspace, patches actual files, and now carries a saved replay capture instead
          of just a scoreline.
        </p>
      </div>

      <div className="live-arena__meta">
        <span>{dataset.source}</span>
        <span>{generatedAt}</span>
        <span>{dataset.fights.length} executed fights</span>
        <span>{dataset.tasks.length} fixture tasks</span>
        <span>{providerSummary} providers</span>
      </div>

      <div className="live-arena__grid">
        <article className="live-arena-card live-arena-card--champion">
          <p className="eyebrow">Live Champion</p>
          <strong>{summary.champion.agent.name}</strong>
          <p>{summary.champion.agent.tagline}</p>
          <div className="live-arena-card__stats">
            <span>{summary.champion.elo} Elo</span>
            <span>
              {summary.champion.wins}-{summary.champion.losses}
            </span>
            <span>{summary.champion.finishes} finishes</span>
          </div>
        </article>

        <article className="live-arena-card">
          <p className="eyebrow">How It Runs</p>
          <ul className="live-note-list">
            {dataset.notes.map((note) => (
              <li key={note}>{note}</li>
            ))}
          </ul>
        </article>
      </div>

      <div className="live-arena__columns">
        <div className="panel panel--inner">
          <p className="eyebrow">Live Ladder</p>
          <h3>Top operators in the current fixture season</h3>
          <div className="live-rankings">
            {summary.rankings.map((row, index) => (
              <article className="live-ranking-row" key={row.agent.id}>
                <span>{String(index + 1).padStart(2, "0")}</span>
                <strong>{row.agent.name}</strong>
                <span>
                  {row.wins}-{row.losses}
                </span>
                <span>{row.elo} Elo</span>
              </article>
            ))}
          </div>
        </div>

        <div className="panel panel--inner">
          <p className="eyebrow">Replay Vault</p>
          <h3>Pick a bout and inspect the saved capture</h3>
          <div className="live-fight-list">
            {summary.fights.map((fight) => {
              const fightTask = summary.taskMap.get(fight.taskId);
              const isActive = fight.id === selectedFight.id;
              const watchable = hasReplayCapture(fight.blue) || hasReplayCapture(fight.red);

              return (
                <button
                  className={`live-fight-row${isActive ? " live-fight-row--active" : ""}`}
                  key={fight.id}
                  onClick={() => setSelectedFightId(fight.id)}
                  type="button"
                >
                  <div>
                    <strong>{fight.headline}</strong>
                    <p>{fightTask?.name}</p>
                  </div>
                  <div className="live-fight-row__meta">
                    <span>{fight.finish}</span>
                    <span>{fight.venue}</span>
                    <span>{watchable ? "Replay saved" : "Score only"}</span>
                  </div>
                </button>
              );
            })}
          </div>
        </div>
      </div>

      <div className="panel panel--inner live-replay">
        <div className="live-replay__header">
          <div>
            <p className="eyebrow">Fight Inspector</p>
            <h3>{selectedFight.headline}</h3>
            <p className="live-replay__copy">
              {task?.description ?? "Replay the captured corner work, logs, and fixture verdict."}
            </p>
          </div>
          <div className="live-arena__meta">
            <span>{selectedFight.finish}</span>
            <span>{selectedFight.venue}</span>
            <span>{task?.category ?? "Fixture"}</span>
            <span>{replayAvailable ? "Replay ready" : "No capture"}</span>
          </div>
        </div>

        <div className="live-corner-switcher">
          {(["blue", "red"] as const).map((side) => {
            const corner = side === "blue" ? selectedFight.blue : selectedFight.red;
            const agent = summary.agentMap.get(corner.agentId);
            const isActive = side === selectedCorner;

            return (
              <button
                className={`live-corner-tab${isActive ? " live-corner-tab--active" : ""}`}
                key={side}
                onClick={() => setSelectedCorner(side)}
                type="button"
              >
                <span>{side === "blue" ? "Blue corner" : "Red corner"}</span>
                <strong>{agent?.name ?? corner.agentId}</strong>
                <small>{corner.capture?.provider ?? "scripted"}</small>
              </button>
            );
          })}
        </div>

        <div className="live-replay__matchup">
          <article className="live-corner-card live-corner-card--active">
            <p className="eyebrow">{selectedCorner === "blue" ? "Blue corner" : "Red corner"}</p>
            <strong>{activeAgent?.name ?? activeCorner.agentId}</strong>
            <p>{activeCorner.diffSummary}</p>
            <div className="live-arena__meta">
              <span>{activeCorner.capture?.provider ?? "scripted"}</span>
              {activeCorner.capture?.model ? <span>{activeCorner.capture.model}</span> : null}
              {activeDuration ? <span>{activeDuration}</span> : null}
              {activeCorner.capture?.tokenEstimateK ? (
                <span>{activeCorner.capture.tokenEstimateK}k tokens</span>
              ) : null}
            </div>
          </article>

          <article className="live-corner-card">
            <p className="eyebrow">Opposing corner</p>
            <strong>{inactiveAgent?.name ?? inactiveCorner.agentId}</strong>
            <p>{inactiveCorner.diffSummary}</p>
            <div className="live-arena__meta">
              <span>{inactiveCorner.capture?.provider ?? "scripted"}</span>
              {inactiveCorner.capture?.model ? <span>{inactiveCorner.capture.model}</span> : null}
              {inactiveCorner.capture?.durationMs ? (
                <span>{formatDuration(inactiveCorner.capture.durationMs)}</span>
              ) : null}
              {inactiveCorner.capture?.tokenEstimateK ? (
                <span>{inactiveCorner.capture.tokenEstimateK}k tokens</span>
              ) : null}
            </div>
          </article>
        </div>

        <div className="live-replay__body">
          <div className="live-transcript">
            <div className="live-section-head">
              <p className="eyebrow">Transcript</p>
              <h3>Saved moves from the selected corner</h3>
            </div>

            {transcript.length > 0 ? (
              <div className="live-transcript__list">
                {transcript.map((entry, index) => (
                  <article
                    className={`live-transcript-entry live-transcript-entry--${entry.channel}`}
                    key={`${entry.channel}-${index}`}
                  >
                    <div className="live-transcript-entry__meta">
                      <span>{getTranscriptLabel(entry)}</span>
                      {entry.atMs !== undefined ? <span>{entry.atMs}ms</span> : null}
                    </div>
                    <p>{entry.text}</p>
                  </article>
                ))}
              </div>
            ) : (
              <div className="live-empty-state">
                <strong>No live capture saved for this corner.</strong>
                <p>The bout still scores normally, but there is no transcript or CLI log to replay.</p>
              </div>
            )}
          </div>

          <div className="live-sidecar">
            <article className="live-sidecar-card">
              <p className="eyebrow">Corner Notes</p>
              <div className="live-chip-grid">
                <span>{activeCorner.promptStyle}</span>
                {activeCorner.capture?.changedFiles?.length ? (
                  <span>{activeCorner.capture.changedFiles.length} files touched</span>
                ) : null}
                {activeCorner.capture?.changedLineCount ? (
                  <span>{activeCorner.capture.changedLineCount} lines touched</span>
                ) : null}
                <span>{activeCorner.metrics.correctness} correctness</span>
                <span>{activeCorner.metrics.diffQuality} diff quality</span>
              </div>
              {activeCorner.capture?.workspaceNotes?.length ? (
                <ul className="live-note-list">
                  {activeCorner.capture.workspaceNotes.map((note) => (
                    <li key={note}>{note}</li>
                  ))}
                </ul>
              ) : (
                <p className="live-sidecar-card__empty">No extra warnings were captured for this corner.</p>
              )}
            </article>

            {activeCorner.capture?.stdoutTail ? (
              <details className="live-log-card">
                <summary>stdout tail</summary>
                <pre>{activeCorner.capture.stdoutTail}</pre>
              </details>
            ) : null}

            {activeCorner.capture?.stderrTail ? (
              <details className="live-log-card">
                <summary>stderr tail</summary>
                <pre>{activeCorner.capture.stderrTail}</pre>
              </details>
            ) : null}
          </div>
        </div>
      </div>
    </section>
  );
}
